In [9]:
import pandas as pd

titanic = pd.read_csv("bases/titanic.csv", sep = ",")

In [12]:
titanic.head() # mostra as 5 primeiras linhas

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
titanic.tail() # mostra as 5 últimas linhas

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [6]:
print(type(titanic))
# pandas.core.frame.DataFrame
# DataFrame é uma classe do pandas que representa os dados de forma tabular, parecendo muito com uma tabela do Excel.

<class 'pandas.core.frame.DataFrame'>

In [5]:
#5 linhas podem não ser o suficiente
titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [6]:
#Podemos indexar nosso Dataframe para vermos os dados de somente uma coluna.
titanic["Name"].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [12]:
# Podemos acessar pelo ponto também!
titanic.Name.head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [13]:
#Dimensão dos dados:
titanic.shape

(891, 12)

In [ ]:
#Ao importar o CSV, o Dataframe inclui uma coluna index, que não está no arquivo. Essa coluna é tipo um índice de linha do Excel.
titanic.index

In [14]:
#Traz os nomes das colunas
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [15]:
#Traz os formatos dos dados
titanic.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [19]:
#filtrando por tipos - qual coluna é do tipo string
filtro_tipo_numerico = (titanic.dtypes != "object")
print(filtro_tipo_numerico)

PassengerId     True
Survived        True
Pclass          True
Name           False
Sex            False
Age             True
SibSp           True
Parch           True
Ticket         False
Fare            True
Cabin          False
Embarked       False
dtype: bool

In [20]:
#traz os nomes das colunas que são numéricas com base na condição filtro_tipo_numérico
colunas_numericas = titanic.dtypes[filtro_tipo_numerico].index
print(colunas_numericas)

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [21]:
titanic[colunas_numericas].head()

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0            1         0       3  22.0      1      0   7.2500
1            2         1       1  38.0      1      0  71.2833
2            3         1       3  26.0      0      0   7.9250
3            4         1       1  35.0      1      0  53.1000
4            5         0       3  35.0      0      0   8.0500

In [23]:
colunas_selecionadas = ["PassengerId","SibSp","Parch"]
titanic[colunas_selecionadas].head()

   PassengerId  SibSp  Parch
0            1      1      0
1            2      1      0
2            3      0      0
3            4      1      0
4            5      0      0

In [29]:
#caso queira acessar todas as colunas menos a última
menosum = titanic.columns[:-1]
titanic[menosum].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN

In [30]:
titanic.iloc[:,:-1].head() # iloc seleciona os índices por linha e coluna
titanic.iloc[15:, :3].head()

    PassengerId  Survived  Pclass
15           16         1       2
16           17         0       3
17           18         1       2
18           19         0       3
19           20         1       3

In [31]:
titanic.loc[:,["Survived"]].head() # loc seleciona pelo nome das colunas

   Survived
0         0
1         1
2         1
3         1
4         0

In [ ]:
titanic.describe() #pega as colunas numéricas e retorna suas respectivas estatísticas

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [33]:
titanic.Age.describe() #caso eu queira os dados estatísticos de uma coluna somente

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [36]:
titanic.describe(include='all') #caso queira todos os valores, mesmo não sendo numéricos

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,B96 B98,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [ ]:

titanic[["Pclass","Pclass"]].describe()

           Pclass      Pclass
count  891.000000  891.000000
mean     2.308642    2.308642
std      0.836071    0.836071
min      1.000000    1.000000
25%      2.000000    2.000000
50%      3.000000    3.000000
75%      3.000000    3.000000
max      3.000000    3.000000

In [57]:
titanic['Age'].mean()

29.69911764705882

In [59]:
titanic.Age.std() # desvio padrão

14.526497332334042

In [95]:
#importar as colunas crim e medv do dataset bostonhousing, mostrando somente as 14 primeiras linhas

boston = pd.read_csv("BostonHousing.csv").loc[:13,['crim','medv']]

print(boston)

       crim  medv
0   0.00632  24.0
1   0.02731  21.6
2   0.02729  34.7
3   0.03237  33.4
4   0.06905  36.2
5   0.02985  28.7
6   0.08829  22.9
7   0.14455  27.1
8   0.21124  16.5
9   0.17004  18.9
10  0.22489  15.0
11  0.11747  18.9
12  0.09378  21.7
13  0.62976  20.4

In [96]:
titanic["Embarked"].unique() #Podemos verificar todos os valores únicos

array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
titanic["Age"].value_counts() #Contagem de quantas vezes eles aparecem

Age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [ ]:
print(titanic.isna().sum()) #soma os valores nulos por coluna
print(titanic.shape) #antes de excluir
x=titanic.dropna() #excluir todas as linhas com not a number
print(x.shape) #após excluir
print(x.isna().head(15))

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
(891, 12)
(183, 12)
    PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
1         False     False   False  False  False  False  False  False   False
3         False     False   False  False  False  False  False  False   False
6         False     False   False  False  False  False  False  False   False
10        False     False   False  False  False  False  False  False   False
11        False     False   False  False  False  False  False  False   False
21        False     False   False  False  False  False  False  False   False
23        False     False   False  False  False  False  False  False   False
27        False     False   False  False  False  False  False  False   False
52        False     False   False  False  False  False  False  False   False
54        False     False   False  False  False  False  False  False   False
62        False     False   False  False  False  False  False  False   False
66        False     False   False  False  False  False  False  False   False
75        False     False   False  False  False  False  False  False   False
88        False     False   False  False  False  False  False  False   False
92        False     False   False  False  False  False  False  False   False

     Fare  Cabin  Embarked
1   False  False     False
3   False  False     False
6   False  False     False
10  False  False     False
11  False  False     False
21  False  False     False
23  False  False     False
27  False  False     False
52  False  False     False
54  False  False     False
62  False  False     False
66  False  False     False
75  False  False     False
88  False  False     False
92  False  False     False

In [130]:
y=titanic["Age"].fillna(titanic["Age"].mean()) #Preencheer onde é encontrado not a number
print(titanic['Age'].mean())
print(y.head(15))
z=titanic.fillna(200)

29.69911764705882
0     22.000000
1     38.000000
2     26.000000
3     35.000000
4     35.000000
5     29.699118
6     54.000000
7      2.000000
8     27.000000
9     14.000000
10     4.000000
11    58.000000
12    20.000000
13    39.000000
14    14.000000
Name: Age, dtype: float64

In [ ]:
print(round(titanic.groupby("Embarked").mean()["Age"].sort_values()["S"], 5))

In [4]:
filtro_apenas_primeira_classe = titanic["Pclass"] == 1
filtro_apenas_primeira_classe.head()

0    False
1     True
2    False
3     True
4    False
Name: Pclass, dtype: bool

In [5]:
filtro_apenas_primeira_classe = titanic["Pclass"] == 1
titanic[ filtro_apenas_primeira_classe ].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [21]:
filtro = (
(titanic["Pclass"] == 1) & (titanic["Survived"] == 1) |
(titanic["Pclass"] == 3) & (titanic["Survived"] == 0)
)
titanic[filtro]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [105]:
print(round(titanic.groupby("Embarked")["Age"].mean().loc["S"],5))

print(titanic.groupby("Embarked")["Age"].mean().sort_values())

29.4454
Embarked
Q    28.089286
S    29.445397
C    30.814769
Name: Age, dtype: float64

In [2]:
m= pd.read_csv("bases/titanic.csv", sep = ",").fillna("nulo")

procurada = ((m["Embarked"] == 'S') & 
             (m['Age'] == 29) & 
             (m["Pclass"] == 2) & 
             (m["Name"].str.contains("Anne")))

match(titanic[procurada].iloc[0]["Survived"]):
    case 1:
        sobreviveu = "ela sobreviveu!"
    case 0:
        sobreviveu = "ela morreu..."

print(f"A mulher que ele está procurando é {titanic[procurada].iloc[0]["Name"]}, {sobreviveu}")

A mulher que ele está procurando é Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson), ela sobreviveu!

In [3]:
import pandas as pd
titanic = pd.read_csv("bases/titanic.csv", sep=",")
def soma_sibsp_parch(linha):
    return linha["SibSp"] + linha["Parch"] # ou seja, todos os parentes dentro do navio

nova_coluna = titanic.apply(soma_sibsp_parch, axis=1)

nova_coluna.head()

0    1
1    1
2    0
3    1
4    0
dtype: int64

In [14]:
def verifica_idade(linha):
    if linha["Age"] < 12:
        return "Criança"
    
    elif linha["Age"] < 18:
        return "Adolescente"
    
    elif linha["Age"] < 65:
        return "Adulto"
    
    elif linha["Age"] >= 65:
        return "Idoso"
    else:
        return "nulo"

faixa_etaria = titanic.apply(verifica_idade, axis=1)

titanic["Age Group"] = faixa_etaria

print(titanic[["Age","Age Group"]].head(50))

     Age    Age Group
0   22.0       Adulto
1   38.0       Adulto
2   26.0       Adulto
3   35.0       Adulto
4   35.0       Adulto
5    NaN         nulo
6   54.0       Adulto
7    2.0      Criança
8   27.0       Adulto
9   14.0  Adolescente
10   4.0      Criança
11  58.0       Adulto
12  20.0       Adulto
13  39.0       Adulto
14  14.0  Adolescente
15  55.0       Adulto
16   2.0      Criança
17   NaN         nulo
18  31.0       Adulto
19   NaN         nulo
20  35.0       Adulto
21  34.0       Adulto
22  15.0  Adolescente
23  28.0       Adulto
24   8.0      Criança
25  38.0       Adulto
26   NaN         nulo
27  19.0       Adulto
28   NaN         nulo
29   NaN         nulo
30  40.0       Adulto
31   NaN         nulo
32   NaN         nulo
33  66.0        Idoso
34  28.0       Adulto
35  42.0       Adulto
36   NaN         nulo
37  21.0       Adulto
38  18.0       Adulto
39  14.0  Adolescente
40  40.0       Adulto
41  27.0       Adulto
42   NaN         nulo
43   3.0      Criança
44  19.0       Adulto
45   NaN         nulo
46   NaN         nulo
47   NaN         nulo
48   NaN         nulo
49  18.0       Adulto

In [15]:
titanic["Relatives"] = nova_coluna
titanic.to_csv("bases/titanic_alterado.csv",index=False)