In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('CSVs/fish_detail.csv')
df.columns

Index(['Name', 'Description', 'Location', 'Time', 'Season', 'Weather',
       'Size (inches)', 'Difficulty & Behavior', 'Base XP', 'Used In'],
      dtype='object')

In [3]:
df.drop(['Used In','Description'],axis=1,inplace=True)

In [4]:
def get_difficulty(line):
    return line['Difficulty & Behavior'][:2]

df['Difficulty'] = df.apply(get_difficulty,axis=1)
df.head()

,Name,Location,Time,Season,Weather,Size (inches),Difficulty & Behavior,Base XP,Difficulty
0,Pufferfish,"Ocean, Ginger Island oceans",12pm – 4pm,Summer\n(All Seasons on Ginger Island),Sun,1-37,80 floater,29,80
1,Anchovy,Ocean,Anytime,Spring\n Fall,Any,1-17,30 dart,13,30
2,Tuna,"Ocean, Ginger Island oceans",6am – 7pm,Summer\n Winter\n(All Seasons on Ginger Island),Any,12-61,70 smooth,26,70
3,Sardine,Ocean,6am – 7pm,Spring\n Fall\n Winter,Any,1-13,30 dart,13,30
4,Bream,River (Town+Forest),6pm – 2am,All Seasons,Any,12-31,35 smooth,14,35

In [5]:
def get_behavior(line):
    return line['Difficulty & Behavior'][3:]

df['Behavior'] = df.apply(get_behavior,axis=1)
df.head()

,Name,Location,Time,Season,Weather,Size (inches),Difficulty & Behavior,Base XP,Difficulty,Behavior
0,Pufferfish,"Ocean, Ginger Island oceans",12pm – 4pm,Summer\n(All Seasons on Ginger Island),Sun,1-37,80 floater,29,80,floater
1,Anchovy,Ocean,Anytime,Spring\n Fall,Any,1-17,30 dart,13,30,dart
2,Tuna,"Ocean, Ginger Island oceans",6am – 7pm,Summer\n Winter\n(All Seasons on Ginger Island),Any,12-61,70 smooth,26,70,smooth
3,Sardine,Ocean,6am – 7pm,Spring\n Fall\n Winter,Any,1-13,30 dart,13,30,dart
4,Bream,River (Town+Forest),6pm – 2am,All Seasons,Any,12-31,35 smooth,14,35,smooth

In [6]:
df.drop('Difficulty & Behavior',axis=1,inplace=True)

In [7]:
df.head()

,Name,Location,Time,Season,Weather,Size (inches),Base XP,Difficulty,Behavior
0,Pufferfish,"Ocean, Ginger Island oceans",12pm – 4pm,Summer\n(All Seasons on Ginger Island),Sun,1-37,29,80,floater
1,Anchovy,Ocean,Anytime,Spring\n Fall,Any,1-17,13,30,dart
2,Tuna,"Ocean, Ginger Island oceans",6am – 7pm,Summer\n Winter\n(All Seasons on Ginger Island),Any,12-61,26,70,smooth
3,Sardine,Ocean,6am – 7pm,Spring\n Fall\n Winter,Any,1-13,13,30,dart
4,Bream,River (Town+Forest),6pm – 2am,All Seasons,Any,12-31,14,35,smooth

In [8]:
dft = df.copy()
dft['Location'] = dft['Location'].str.replace('\n', ',')
dft['Location'] = dft['Location'].str.split(',')
dft = dft.explode('Location')
dft.head()

,Name,Location,Time,Season,Weather,Size (inches),Base XP,Difficulty,Behavior
0,Pufferfish,Ocean,12pm – 4pm,Summer\n(All Seasons on Ginger Island),Sun,1-37,29,80,floater
0,Pufferfish,Ginger Island oceans,12pm – 4pm,Summer\n(All Seasons on Ginger Island),Sun,1-37,29,80,floater
1,Anchovy,Ocean,Anytime,Spring\n Fall,Any,1-17,13,30,dart
2,Tuna,Ocean,6am – 7pm,Summer\n Winter\n(All Seasons on Ginger Island),Any,12-61,26,70,smooth
2,Tuna,Ginger Island oceans,6am – 7pm,Summer\n Winter\n(All Seasons on Ginger Island),Any,12-61,26,70,smooth

In [12]:
dfn = df.copy()
dfn['Season'] = dfn['Season'].str.replace('\n',',')
dfn['Season'] = dfn['Season'].str.replace(',(All Seasons on Ginger Island)','',regex=False).str.strip()
dfn['Season'] = dfn['Season'].str.split(',')
dfn = dfn.explode('Season')
dfn

,Name,Location,Time,Season,Weather,Size (inches),Base XP,Difficulty,Behavior
0,Pufferfish,"Ocean, Ginger Island oceans",12pm – 4pm,Summer,Sun,1-37,29,80,floater
1,Anchovy,Ocean,Anytime,Spring,Any,1-17,13,30,dart
1,Anchovy,Ocean,Anytime,Fall,Any,1-17,13,30,dart
2,Tuna,"Ocean, Ginger Island oceans",6am – 7pm,Summer,Any,12-61,26,70,smooth
2,Tuna,"Ocean, Ginger Island oceans",6am – 7pm,Winter,Any,12-61,26,70,smooth
...,...,...,...,...,...,...,...,...,...
42,Void Salmon,Witch's Swamp,Anytime,All Seasons,Any,24-66,29,80,mixed
43,Slimejack,Mutant Bug Lair,Anytime,All Seasons,Any,8-26,21,55,dart
44,Stingray,Pirate Cove (Ginger Island),Anytime,All Seasons,Any,18-61,29,80,sinker
45,Lionfish,Ginger Island Ocean,Anytime,All Seasons,Any,3-13,19,50,smooth
46,Blue Discus,Ginger Island Pond and Rivers,Anytime,All Seasons,Any,2-10,23,60,dart

In [10]:
dff = df.copy()

dff['Location'] = dff['Location'].str.replace('\n', ',', regex=False)
dff['Location'] = dff['Location'].str.replace('*Requires fishing level 4*','',regex=False).str.strip()
dff['Location'] = dff['Location'].str.split(',')

dff['Season'] = dff['Season'].str.replace('\n',',')
dff['Season'] = dff['Season'].str.replace(',(All Seasons on Ginger Island)','',regex=False).str.strip()
dff['Season'] = dff['Season'].str.split(',')

dff = dff.explode('Location')
dff = dff.explode('Season')

dff = dff.dropna().reset_index(drop=True)

dff

,Name,Location,Time,Season,Weather,Size (inches),Base XP,Difficulty,Behavior
0,Pufferfish,Ocean,12pm – 4pm,Summer,Sun,1-37,29,80,floater
1,Pufferfish,Ginger Island oceans,12pm – 4pm,Summer,Sun,1-37,29,80,floater
2,Anchovy,Ocean,Anytime,Spring,Any,1-17,13,30,dart
3,Anchovy,Ocean,Anytime,Fall,Any,1-17,13,30,dart
4,Tuna,Ocean,6am – 7pm,Summer,Any,12-61,26,70,smooth
...,...,...,...,...,...,...,...,...,...
111,Void Salmon,Witch's Swamp,Anytime,All Seasons,Any,24-66,29,80,mixed
112,Slimejack,Mutant Bug Lair,Anytime,All Seasons,Any,8-26,21,55,dart
113,Stingray,Pirate Cove (Ginger Island),Anytime,All Seasons,Any,18-61,29,80,sinker
114,Lionfish,Ginger Island Ocean,Anytime,All Seasons,Any,3-13,19,50,smooth
115,Blue Discus,Ginger Island Pond and Rivers,Anytime,All Seasons,Any,2-10,23,60,dart